#!/bin/bash -l

# Execute given GraphQL file as a query to GDC
# Usage: queryGDC token.txt query.dat
# 
# token.txt contains GDC authentication token (see https://docs.gdc.cancer.gov/Data_Submission_Portal/Users_Guide/Authentication/ )
# query.dat contains "bare queryGL" script (see https://docs.gdc.cancer.gov/API/Users_Guide/Submission/#querying-submitted-data-using-graphql )
#       queryGDC token.txt - 
#   will read query from STDIN

# Matthew A. Wyczalkowski
# m.wyczalkowski@wustl.edu
# Ding Lab, Washington University School of Medicine

function run_query {
    QUERY=$1
    curl -s -XPOST -H "X-Auth-Token: $t" https://gdc-api.nci.nih.gov/v0/submission/graphql --data "$QUERY" 
}

function get_json {
# Creates valid GDC query JSON string based on graphQL data
# For testing, this content of GQL file works:
# { sample(with_path_to: {type: "case", submitter_id:"C3L-00004"}) { id submitter_id sample_type } }


# Escaping, in this context, means converting it to a format that could be
# parsed as a string.  This involves replacing special characters that could
# inhibit parsing, such as newline and tab, with escape sequences, which would
# be "\n" and "\t" respectively.  The following page explains all of the
# replacement and also has a tool that does this:
# https://www.freeformatter.com/json-escape.html

GQL=$1

PY="import json, sys; query = sys.stdin.read().rstrip(); d = { 'query': query, 'variables': 'null' }; print(json.dumps(d))"

if [ $GQL == '-' ]; then
cat - | python -c "$PY"
else
python -c "$PY" < $GQL
fi
}


# Run a query in a given file against GDC server
# where query is file with bare_graphql query (as described here
# https://docs.gdc.cancer.gov/API/Users_Guide/Submission/#querying-submitted-data-using-graphql )

if [ "$#" -ne 2 ]; then
echo Incorrect number of arguments passed: got $#, expecting 2
echo Usage: queryGDC token.txt query.json
exit
fi

#TOKEN="config/gdc-user-token.2017-10-23T18-08-47.214Z.txt"
TOKEN=$1
if [ ! -f $TOKEN ]; then
    echo Token $TOKEN not found
    exit
fi

export t=$(cat $TOKEN)

JSON=$(get_json $2)

run_query "$JSON"

